<?php

return [
    'items' => [
        'residence-point-e-prestige' => [
            'slug' => 'residence-point-e-prestige',
            'title' => 'Residence Point E Prestige',
            'type' => 'Appartement standing',
            'location' => 'Dakar Point E',
            'price' => 'Sur demande',
            'surface' => '180 m2',
            'beds' => 'x3',
            'baths' => 'x3',
            'hero_image' => '/img/all-images/apartment/apartment-img26.png',
            'card_image' => '/img/all-images/apartment/apartment-img1.png',
            'gallery_image_1' => '/img/all-images/apartment/apartment-img27.png',
            'gallery_image_2' => '/img/all-images/apartment/apartment-img28.png',
            'summary' => 'Une residence de standing pensee pour les familles et les investisseurs qui recherchent une adresse forte a Point E.',
            'description_1' => 'Ce produit illustre le type de bien que Sunugal Habitat peut commercialiser et accompagner a Dakar. Il met en avant un emplacement recherché, une belle qualite de construction et un fort potentiel patrimonial.',
            'description_2' => 'Nous cadrons chaque etape: estimation, visites qualifiees, negociation et securisation documentaire. Le but est de vous faire gagner du temps sans perdre en exigence.',
            'amenities_title' => 'Atouts du produit',
            'amenities_text' => 'Chaque fiche produit est preparee pour donner une vision claire du bien, de sa valeur et de son potentiel.',
            'amenities' => [
                'Adresse premium',
                'Pieces lumineuses',
                'Stationnement resident',
                'Patio ou balcon',
                'Cadre residentiel',
                'Potentiel locatif',
            ],
        ],
        'villa-jardin-almadies' => [
            'slug' => 'villa-jardin-almadies',
            'title' => 'Villa Jardin Almadies',
            'type' => 'Villa familiale',
            'location' => 'Dakar Almadies',
            'price' => 'Sur demande',
            'surface' => '240 m2',
            'beds' => 'x4',
            'baths' => 'x4',
            'hero_image' => '/img/all-images/apartment/apartment-img24.png',
            'card_image' => '/img/all-images/apartment/apartment-img2.png',
            'gallery_image_1' => '/img/all-images/apartment/apartment-img23.png',
            'gallery_image_2' => '/img/all-images/apartment/apartment-img22.png',
            'summary' => 'Un produit adapte a une famille recherchant espace, calme et acces rapide aux poles strategiques de Dakar.',
            'description_1' => 'Sunugal Habitat met en avant les biens avec un dossier lisible, des visites ciblees et un accompagnement rassurant pour les acquereurs comme pour les vendeurs.',
            'description_2' => 'Sur ce type de villa, nous travaillons la mise en valeur, la qualification des prospects et la fluidite de la transaction jusqu a la signature.',
            'amenities_title' => 'Atouts du produit',
            'amenities_text' => 'Les informations essentielles sont regroupees pour vous aider a vous positionner rapidement.',
            'amenities' => [
                'Grande parcelle',
                'Distribution familiale',
                'Jardin prive',
                'Bonne accessibilite',
                'Cadre calme',
                'Valorisation revente',
            ],
        ],
        'immeuble-locatif-liberte-6' => [
            'slug' => 'immeuble-locatif-liberte-6',
            'title' => 'Immeuble Locatif Liberte 6',
            'type' => 'Immeuble de rapport',
            'location' => 'Dakar Liberte 6',
            'price' => 'Sur demande',
            'surface' => '520 m2',
            'beds' => 'x8',
            'baths' => 'x8',
            'hero_image' => '/img/all-images/apartment/apartment-img18.png',
            'card_image' => '/img/all-images/apartment/apartment-img3.png',
            'gallery_image_1' => '/img/all-images/apartment/apartment-img19.png',
            'gallery_image_2' => '/img/all-images/apartment/apartment-img20.png',
            'summary' => 'Un actif interessant pour un investisseur qui cherche du rendement locatif et une gestion structuree.',
            'description_1' => 'Sunugal Habitat accompagne ce type d actif sur deux volets: la commercialisation du bien et la preparation de son exploitation locative avec des scenarios clairs.',
            'description_2' => 'Notre role est d aider a arbitrer, projeter les revenus et organiser une mise sur le marche plus professionnelle.',
            'amenities_title' => 'Atouts du produit',
            'amenities_text' => 'La fiche met l accent sur les elements decisifs pour un investisseur ou un proprietaire institutionnel.',
            'amenities' => [
                'Plusieurs lots',
                'Rendement potentiel',
                'Secteur actif',
                'Gestion mutualisee',
                'Travaux pilotables',
                'Valorisation long terme',
            ],
        ],
        'appartement-fann-mermoz' => [
            'slug' => 'appartement-fann-mermoz',
            'title' => 'Appartement Fann Mermoz',
            'type' => 'Appartement familial',
            'location' => 'Dakar Fann Mermoz',
            'price' => 'Sur demande',
            'surface' => '150 m2',
            'beds' => 'x3',
            'baths' => 'x2',
            'hero_image' => '/img/all-images/apartment/apartment-img21.png',
            'card_image' => '/img/all-images/apartment/apartment-img5.png',
            'gallery_image_1' => '/img/all-images/apartment/apartment-img16.png',
            'gallery_image_2' => '/img/all-images/apartment/apartment-img17.png',
            'summary' => 'Un appartement bien situe, adapte a un usage residence principale ou a un placement locatif de qualite.',
            'description_1' => 'Pour ce type de produit, nous mettons l accent sur la clarte des informations, la qualite des visites et la transparence dans la negociation.',
            'description_2' => 'L objectif est de presenter un bien lisible, bien positionne et soutenu par un accompagnement juridique rassurant.',
            'amenities_title' => 'Atouts du produit',
            'amenities_text' => 'Une fiche detaillee facilite la comparaison et accelere la prise de decision.',
            'amenities' => [
                'Secteur recherche',
                'Plan fonctionnel',
                'Bonne ventilation',
                'Acces commodites',
                'Usage mixte possible',
                'Location facile',
            ],
        ],
    ],
];
